apiVersion: v1
kind: Service
metadata:
  name: gitops-connector
spec:
  selector:
    app: gitops-connector   
  ports:
    - port: {{  .Values.containerPort}}
      targetPort: {{  .Values.containerPort}}
