{{ if .Values.subscribers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-connector-subscribers-config
data:
  {{- range $key, $val := .Values.subscribers }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}
