imageName: ghcr.io/azure/gitops-connector
imageTag: 1.2.0
containerPort: 8080

gitRepositoryType: GITHUB
ciCdOrchestratorType: GITHUB
gitOpsOperatorType: FLUX
gitOpsAppURL: https://github.com/kaizentm/gitops-manifests/commit
azdoGitOpsRepoName: test
azdoPrRepoName: 
azdoOrgUrl: 
orchestratorPAT: 

gitHubGitOpsRepoName: gitops-connector
gitHubGitOpsManifestsRepoName: gitops-manifests
gitHubOrgUrl: https://api.github.com/repos/kaizentm

# Optional list of subscriber endpoints to send raw JSON to
#subscribers:
#  sub1: http://localhost:8080/gitopsphase
#  sub2: http://127.0.0.1:1234/

# Optional list of tolerations
# tolerations:
#   - key: kubernetes.azure.com/scalesetpriority
#     operator: Equal
#     value: spot
#     effect: NoSchedule

# Optional node selector rules
# nodeSelector:
#   kubernetes.io/os: linux